#!/bin/sh

texify()
{
  sed 's/\_neg\_flip/^~^/g' \
    | sed 's/\_neg/^~/g' \
    | sed 's/\_flip/^^/g' \
    | sed 's/right\_//g'
}

echo '\\begin{code}' > equivalences.tex
cat implications \
  | grep ' <=> ' \
  | texify \
  | column -t \
  >> equivalences.tex
echo '\\end{code}' >> equivalences.tex

echo '\\begin{code}' > implications.tex
cat implications \
  | grep ' <= ' \
  | texify \
  | sed 's/<=/X<=/g' \
  | column -t -sX \
  >> implications.tex
echo '\\end{code}' >> implications.tex
